// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anuwieaouxuublcfltzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFudXdpZWFvdXh1dWJsY2ZsdHp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE5NTMxMTQsImV4cCI6MjA4NzUyOTExNH0.PSMD9Sw3COI2pqOpKr0AWkpsKEPCxa9pW9pOzuz440s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});